#!/bin/bash
set -e

if which gtk-update-icon-cache >/dev/null 2>&1 ; then
    gtk-update-icon-cache /usr/share/pixmaps
fi

if which update-desktop-database >/dev/null 2>&1 ; then
    update-desktop-database /usr/share/applications
fi
