name: dropshelf
base: core24
version: '0.1.0'
summary: A temporary drag-and-drop shelf for your files.
# Added the icon here so you don't need to manually organize it
icon: gui/icon.png 
description: |
  DropShelf serves as a persistent holding zone to streamline your file management.
  Drag files onto the shelf to store them temporarily and move them to their destination later.
  Browse and preview all your dropped items to keep track of your content.
  Drag images directly from web browsers to download and save them automatically.
  Group multiple text snippets into a single ready-to-use CSV file.

grade: devel
confinement: strict

apps:
  dropshelf:
    command: bin/dropshelf
    extensions: [gnome]
    common-id: com.dropshelf.app
    desktop: usr/share/applications/dropshelf.desktop
    plugs:
      - home
      - removable-media
      - network
      - network-status 
      - desktop
      - desktop-legacy
      - wayland
    slots:
      - dbus-dropshelf

parts:
  dropshelf-code:
    plugin: dump
    source: .
    
    environment:
      GSK_RENDERER: gl
    # We manually copy files to avoid the 'venv' crash
    override-build: |
      # 1. Setup directories
      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/gui

      # 2. Copy and make executable
      cp main.py $CRAFT_PART_INSTALL/bin/dropshelf
      chmod +x $CRAFT_PART_INSTALL/bin/dropshelf

      # 3. Copy assets
      cp gui/dropshelf.desktop $CRAFT_PART_INSTALL/usr/share/applications/
      cp gui/icon.png $CRAFT_PART_INSTALL/gui/

    stage-packages:
      - python3
      - python3-gi
      - libcairo2
      - ca-certificates

slots:
  dbus-dropshelf:
    interface: dbus
    bus: session
    name: com.dropshelf.app
