name: dropshelf
base: core24
version: '0.1.0'
summary: A temporary drag-and-drop shelf for your files.
description: |

DropShelf serves as a persistent holding zone to streamline your file management.
  Drag files onto the shelf to store them temporarily and move them to their destination later.
  Browse and preview all your dropped items to keep track of your content.
  Drag images directly from web browsers to download and save them automatically.
  Group multiple text snippets into a single ready-to-use CSV file.

grade: devel
confinement: strict

apps:
  dropshelf:
    command: bin/dropshelf
    extensions: [gnome]
    common-id: com.dropshelf.app
    desktop: usr/share/applications/dropshelf.desktop
    plugs:
      - home
      - removable-media
      - network
      # 'network-status' is often helpful if you want to check connection before downloading
      - network-status 
      - desktop
      - desktop-legacy
      - wayland
    slots:
      - dbus-dropshelf

parts:
  dropshelf-code:
    plugin: dump
    source: .
    organize:
      main.py: bin/dropshelf
      gui/dropshelf.desktop: usr/share/applications/dropshelf.desktop
      gui/icon.png: meta/gui/icon.png
    
    # --- FIX 1: Ensure the script is executable ---
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/bin/dropshelf

    stage-packages:
      - python3
      - python3-gi
      - libcairo2
      # --- FIX 2: Required for downloading images via HTTPS ---
      - ca-certificates 

slots:
  dbus-dropshelf:
    interface: dbus
    bus: session
    name: com.dropshelf.app
